### ISSUE TITLE
USER STORY: Sample3

### ISSUE THREAD

**Issue by Patrick5009** [Patrick5009/My-first-agile-projest#10]
As a **role** I can **capability** so that **received benefit** e.g.
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

# Acceptance Criteria
- Acceptance Criteria 1: e.g. The option should be provided as a checkbox
- Acceptance Criteria 2: e.g. The checkbox should be checked by default
- Acceptance Criteria 3: e.g. The option should appear next to the submit button
- Acceptance Criteria 4: e.g. After submitting th default submission confirmation should be adjusted to include the user name
# Tasks
- [ ] Task 1 e.g. Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Task 2 e.g Create a new field in the model to track the username
- [ ] Task 3 e.g Update the controller function
- [ ] Task 4 e.g. Update unit test scripts
- [ ] Task 5 Test the functionality
