### ISSUE TITLE
USER STORY: Hide poll as admin, pick expiry date while publishing

### ISSUE THREAD

**Issue by Patrick5009** [Patrick5009/My-first-agile-projest#6]
In order to automatically hide the pole as an administrator, I can pick the expiry date while publishing the poll

# Acceptance Criteria
- Acceptance Criteria 1: The pole should disappear at 11:59 on the target date
- Acceptance Criteria 2: The real estate of the "poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other poll is active
- Acceptance Criteria 3: The administrator expiry date should be at least 3 days after the expiry date

# Tasks
- [ ] Task 1 Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Task 2 Update the website view: show "stay tuned, a new pole is coming soon"
- [ ] Task 3 Create a Javascript function to validate the expiry date is at least after 3 days.
- [ ] Task 4 Create a job to check expired polls everyday at 11:59 PM and hide them
- [ ] Task 5 Update the controller function
- [ ] Task 6 Update unit test scripts
- [ ] Task 7 Test the functionality
